import Head from "next/head";
import React, { useState, Fragment } from "react";
import moment from "moment";
import styles from "../styles/Home.module.scss";
import SplitButton from "../components/Formatters/SplitButton/SplitButton";


export default function Home() {
  const [information, setInformation] = useState("Informations suplémentaires");
  const finalRowList = [
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Pour les dates qui depassent.",
      granularity: ['minutes', 'days'],
      dates: [ moment().add(24, "days").add(35, "minutes"), moment().add(0, "days")],
      status: "active",
      tooltip: "normal",
    },
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Vous n'êtes pas très beau",
      granularity: ['minutes', 'days'],
      dates: [ moment().add(0, "days").add(1, "minutes"), moment().add(0, "days").add(238, "minutes")],
      status: "stand-by",
      tooltip: "normal",
    },
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Vous n'êtes pas très beau",
      status: "done",
      granularity: ['minutes', 'days', 'weeks', 'months'],
      dates: [ moment().add(4, "days").add(352, "minutes"), moment().add(48, "days")],
      tooltip: "composed",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sideblock}>
        <SplitButton />
      </div>
    </div>
  );
}
