import Head from "next/head";
import React, { useState, Fragment } from "react";
import moment from "moment";
import styles from "../styles/Home.module.scss";
import DateFormatter from "../components/Formatters/DateFormatter/DateFormatter";
import stylesTooltip from "../components/Tooltips/tooltip.module.scss";
import Example from "../components/Tooltips/Example";


export default function Home() {
  const [information, setInformation] = useState("Informations suplémentaires");
  const finalRowList = [
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Pour les dates qui depassent.",
      granularity: ['minutes', 'days'],
      dates: [ moment().add(24, "days").add(35, "minutes"), moment().add(0, "days")],
      status: "active",
      tooltip: "normal",
    },
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Vous n'êtes pas très beau",
      granularity: ['minutes', 'days'],
      dates: [ moment().add(0, "days").add(1, "minutes"), moment().add(0, "days").add(238, "minutes")],
      status: "stand-by",
      tooltip: "normal",
    },
    {
      content: "David Zephari",
      date: new Date(Date.now()),
      message: "Vous n'êtes pas très beau",
      status: "done",
      granularity: ['minutes', 'days', 'weeks', 'months'],
      dates: [ moment().add(4, "days").add(352, "minutes"), moment().add(48, "days")],
      tooltip: "composed",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.body}>
          <div className={styles.container}>
            {finalRowList.map((item, idx) => (
              <React.Fragment key={idx}>
                <div className={styles.row}>
                  <div
                    className={[styles.item, stylesTooltip.tooltip].join(" ")}
                    data-tooltip={item.status}
                  >
                    {item.status}
                  </div>
                  <div className={styles.item}>
                    <DateFormatter
                      tooltip={item.tooltip}
                      date={item.dates[0]}
                      dates={item.dates}
                      style="invalid"
                      format={"DD/MM/YYYY"}
                      granularity={item.granularity}
                    />
                  </div>
                  <div className={styles.item}>
                    <Example />
                  </div>
                  <div className={styles.item}>
                  <DateFormatter    
                      tooltip={item.tooltip}    
                      date={item.dates[0]}
                      dates={item.dates}
                      format={"LL"}
                      granularity={item.granularity}
                      variant={'composed'}
                      paletteState={[{state: true, palette: 'valid'}, {state: true, palette: 'invalid'}]}
                    />
                    </div>
                  <div
                    className={[styles.item, stylesTooltip.tooltip].join(" ")}
                    data-tooltip={item.message}
                  >
                    {item.message}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
